# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DemSlicer
                                 A QGIS plugin
 D.E.M. slicer, produces lines
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-10-24
        copyright            : (C) 2019 by xc
        email                : xavier.culos@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DemSlicer class from file DemSlicer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .dem_slicer import DemSlicer
    return DemSlicer(iface)
