name: Packager 📦

env:
  PROJECT_FOLDER: "dem_slicer"
  PYTHON_VERSION: 3.8

on:
  push:
    tags:
      - '*'

jobs:
  packaging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - uses: actions/cache@v2.1.7
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install project requirements
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install -U 'qgis-plugin-ci>=1.8,<1.9'

      - name: Package the latest version
        run: |
          qgis-plugin-ci package ${GITHUB_REF/refs\/tags\//}

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PROJECT_FOLDER }}-${{ GITHUB_REF/refs\/tags\// }}
          path: ${{ env.PROJECT_FOLDER }}.${{ GITHUB_REF/refs\/tags\// }}.zip
          if-no-files-found: error
