name: Packager 📦

env:
  PROJECT_FOLDER: "dem_slicer"
  PYTHON_VERSION: 3.8

on:
  push:
    tags:
      - 'v*.*'

jobs:
  packaging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - uses: actions/cache@v2.1.7
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install project requirements
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install -U 'qgis-plugin-ci>=1.8,<1.9'

      - name: Package the latest version
        run: |
          qgis-plugin-ci package $GITHUB_REF_NAME

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PROJECT_FOLDER }}-${{ github.ref_name }}
          path: ${{ env.PROJECT_FOLDER }}.${{ github.ref_name }}.zip
          if-no-files-found: error
