name: Packager 📦

env:
  PROJECT_FOLDER: "dem_slicer"
  PYTHON_VERSION: 3.8

on:
  push:
    tags:
      - 'v*.*'

jobs:
  packaging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set env
        run: echo "PLUGIN_TAGNAME=$(echo ${GITHUB_REF_NAME:1})" >> $GITHUB_ENV

      - name: Test tagname
        run: |
          echo $PLUGIN_TAGNAME
          echo ${{ env.PLUGIN_TAGNAME }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - uses: actions/cache@v2.1.7
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install project requirements
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install -U 'qgis-plugin-ci>=1.8,<1.9'

      - name: Package the latest version
        run: |
          qgis-plugin-ci package $PLUGIN_TAGNAME

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PROJECT_FOLDER }}-${{ env.PLUGIN_TAGNAME }}
          path: ${{ env.PROJECT_FOLDER }}.${{ env.PLUGIN_TAGNAME }}.zip
          if-no-files-found: error
